### ISSUE TITLE
Concurrent access

### ISSUE THREAD

**Issue by rarkins** [zaaack/keyv-file#3]
Hi, thanks for releasing this package. I would like to use this with 2+ processes reading/writing to this keyv file at the same time - are there any concerns about data loss or corruption if so?

**Comment by zaaack** [comment]
Yeah, this package doesn't consider multi-process reading/writing, it loads all data in memory when initializing, and write to disk with delay after each set. It cannot handle  2+ processes case. It's an adapter of keyv, you can check out other adapters, like keyv-redis, keyv-mysql, etc.

**Comment by fabiante** [comment]
Just now I am trying out this package and I will also have to deal with this.

I'd recommend using a lock.

**Comment by zaaack** [comment]
@FabianTe If you don't need share data for different processes, you can add processId in cache filename. Adding lock will affecting the performance, because it holds all data in memeory. If lock is what you need, perhaps radis/memcached/leveldb etc. might be a better choice.

**Comment by fabiante** [comment]
Thanks for the answer @zaaack. Sadly I can't use an actual database, an annoying constraint of my project.

As far as performance goes that isn't really an issue because I will access the file only once per hour.

But still, I have a question about the writing: In your code example in the readme you wrote:

> ms, batch write to disk in a specific duration, enhance write performance.

Is this batch write caused by an operation on the keyv object or async in the background? If it happens in the background, I guess that a lock wouldn't make any sense, correct?

**Comment by zaaack** [comment]
@FabianTe seting on keyv object in memory is synchronized, but writing to disck is asynchronized and  happens in the background, but you can force flush to disk via 

```ts
kv.set('aa', 'bb') // set data and it will trigger batch writing task to disk in background 
await kv.save() // save to disk manually and wait until it's done, if there is already a writing task it will return and wait unitl it's done.
```
